First attempt at logging to files instead of std out
dtekcth/mat-chalmers pull request #135
Opened 2024-09-25 19:00 UTC by The1Penguin

2024-09-25 19:12 UTC, SwedishSubmarine approved these changes
Looks good to me. Not sure how to unit test this but shouldn't break anything either way so worth trying.

2024-09-25 19:20 UTC, Rembane requested changes
Damn good initiative if I may say so myself!

See the comments for confusion, hearts and questions!

2024-09-25 19:20 UTC, Rembane commented on app/Main.hs
> +import           System.Directory                         ( createDirectoryIfMissing )
:tada:  IT EXISTS FOR REAL! :tada:

2024-09-25 19:20 UTC, Rembane commented on app/Main.hs
> +  , Option [] ["path"] (ReqArg (set cLogPath) "PATH") "Path to save log files to, default is 'logs'"
```suggestion
  , Option [] ["path"] (ReqArg (set cLogPath) "PATH")     "Path to save log files to, default is 'logs'"
```

Columns <3

2024-09-25 19:20 UTC, Rembane commented on app/Main.hs
> +    createDirectoryIfMissing True (_cLogPath config)
Is this path relative?

2024-09-25 19:20 UTC, Rembane commented on app/Main.hs
> +    createDirectoryIfMissing True (_cLogPath config)
Or maybe both?

2024-09-25 19:20 UTC, Rembane commented on app/Main.hs
> +    createDirectoryIfMissing True (_cLogPath config)
Both absolute and relative that is

2024-09-25 19:20 UTC, Rembane commented on src/Model.hs
> +                                                          , getZonedTime, getCurrentTime
```suggestion
                                                          , getCurrentTime
                                                          , getZonedTime
```

2024-09-25 19:20 UTC, Rembane commented on src/Model.hs
> +                                                          , getZonedTime, getCurrentTime
Newlines and lexicographic ordering <3

2024-09-25 19:41 UTC, Multipacker approved these changes
Looks good, just a minor indentation fix

2024-09-25 19:41 UTC, Multipacker commented on src/Model.hs
> +import Text.Printf (printf)
Minor indentation fix
```suggestion
import           Model.Linsen
import           Text.Printf (printf)
```

2024-09-25 19:46 UTC, The1Penguin commented on app/Main.hs
> +    createDirectoryIfMissing True (_cLogPath config)
It handles both :D :dagger:

2024-09-25 20:15 UTC, Rembane commented on app/Main.hs
> +    createDirectoryIfMissing True (_cLogPath config)
AWESOME! I am now a much calmer human.

2024-09-25 20:26 UTC, Rembane commented
Something just struck me, this is me thinking aloud, I think it's faster and uses less resources to write to file as a `ByteString` or `Text`, OTOH I think we'll have to go through `String` anyway, so maybe it doesn't matter?

2024-09-25 20:50 UTC, The1Penguin commented
> Something just struck me, this is me thinking aloud, I think it's faster and uses less resources to write to file as a `ByteString` or `Text`, OTOH I think we'll have to go through `String` anyway, so maybe it doesn't matter?

Ignored :dagger:

2024-09-26 09:36 UTC, Rembane approved these changes
I've done art! You can use it if you want to. :smile_cat:

2024-09-26 09:42 UTC, merged