Moved Main.hs to app/Main.hs and cleaned up the cabal file. Closes #43.
dtekcth/mat-chalmers pull request #45
Opened 2018-12-30 22:04 UTC by Rembane

Removed all descriptive comments from mat-chalmers.cabal. We do not need
them anymore.

2018-12-30 23:33 UTC, Jassob requested changes
I think we should attempt to keep the PR titles short and concise and also keep PR's in general, but commits particularly, as narrow in scope as possible.

I would, for example, split up the cleanup of the cabal file in one commit and the file rename and cabal file update in another.

2018-12-31 10:10 UTC, Rembane commented
Sure! I fix! Laziness got the better of me. Too much Haskell! :D

2018-12-31 11:20 UTC, Rembane commented
@Jassob What about this instead?

2018-12-31 11:29 UTC, Jassob approved these changes

2018-12-31 11:43 UTC, merged